# Generated by Django 3.0.6 on 2020-05-17 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='picture',
        ),
    ]
